"use strict";

// WARNING - do not edit this file - used for tests

module.exports = {
    "index": {
        "example": {
            "hash": true,
            "auth": {
                "username": true,
                "api_key": true
            }
        }
    }
};